#!/usr/bin/env julia

# Diagnostic-only: test whole-ROI sequence recovery with converged ±0.80 nm
# periodic DFT molds. Requires /tmp/opencode periodic080 artifacts.
#
# This script generates a synthetic chain observation by placing real DFT molds
# at known positions with a known type sequence, adds a Gaussian backbone and
# background, then asks the whole-ROI search to recover the sequence.
# It does NOT use benchmark labels, expected N, or the control sequence.
#
# Usage:
#   julia --project=. test/diagnose_joint_proxy_whole_roi_converged.jl
#
# Prerequisites:
#   /tmp/opencode/chitosan_connected_molds_dft_m030_h050_periodic080_half080.tsv
#   (generated by test/cube_to_stm_maps.jl --periodic-axes xy --half-nm 0.80)

using Printf
using Random

include(joinpath(@__DIR__, "lib", "joint_proxy", "proxy_registry.jl"))
include(joinpath(@__DIR__, "diagnose_joint_proxy_whole_roi.jl"))

const WR_REG = Main.JointProxyRegistry

function load_converged_entry(path::String)
    isfile(path) || error("converged mold TSV not found: $path\n" *
        "Generate with: julia --project=. test/cube_to_stm_maps.jl " *
        "--periodic-axes xy --half-nm 0.80 ...")
    templates = WR_REG.load_stm_template_tsv(path; npix=441)
    source = WR_REG.ProxySource("stm_dft_periodic080", "converged_diagnostic",
        path, WR_REG.sha256_file(path), 0.50, 1.0, true)
    return WR_REG.ProxyEntry(source, templates)
end

function _template_pixels(entry, typ, parity, mirror)
    for t in entry.templates
        if t.type == typ && t.parity == parity && t.mirror == mirror
            return t.pixels
        end
    end
    error("missing template type=$typ parity=$parity mirror=$mirror")
end

function synthetic_converged_chain(entry, half_nm, step_nm;
        n=3, spacing_nm=0.52, theta=0.0,
        sequence=[0, 1, 0], direction=0, phase=0, mirror=0,
        background=0.3, backbone_amp=0.8, mold_amp=0.4,
        noise_sigma=0.0, seed=20260724)

    grid_n = length(collect(-half_nm:step_nm:half_nm))
    cos_th, sin_th = cos(theta), sin(theta)
    t_start = -(n - 1) * spacing_nm / 2.0
    centers = [(t_start + (k - 1) * spacing_nm, 0.0) for k in 1:n]

    # ROI grid: wider than the chain to capture full mold extent
    roi_half = max(half_nm + 0.2, (n - 1) * spacing_nm / 2 + half_nm + 0.1)
    xs = collect(-roi_half:step_nm:roi_half)
    ys = collect(-half_nm - 0.1:step_nm:half_nm + 0.1)

    # Assemble the mold image
    mold_image = assemble_whole_roi(entry, sequence, centers, xs, ys;
        half_nm=half_nm, step_nm=step_nm, theta=theta,
        direction=direction, phase=phase, mirror=mirror)

    # Gaussian backbone (per-lobe)
    backbone = zeros(Float64, length(ys), length(xs))
    sigma_par = 0.20
    sigma_perp = 0.14
    for k in 1:n
        cx, cy = centers[k]
        for iy in eachindex(ys), ix in eachindex(xs)
            dx = xs[ix] - cx
            dy = ys[iy] - cy
            backbone[iy, ix] += exp(-0.5 * (dx^2 / sigma_par^2 + dy^2 / sigma_perp^2))
        end
    end

    observed = background .+ backbone_amp .* backbone .+ mold_amp .* mold_image

    if noise_sigma > 0
        rng = MersenneTwister(seed)
        observed .+= noise_sigma .* randn(rng, size(observed))
    end

    return (; observed, backbone, mold_image, centers, xs, ys,
        sequence, theta, direction, phase, mirror)
end

function main()
    mold_path = "/tmp/opencode/chitosan_connected_molds_dft_m030_h050_periodic080_half080.tsv"
    entry = load_converged_entry(mold_path)
    half_nm = 0.80
    step_nm = 0.08

    println("Converged whole-ROI diagnostic")
    println("  molds:  ", mold_path)
    println("  grid:   21x21 (441 pixels)")
    println()

    # Test 1: exact recovery with no noise
    for true_sequence in ([0, 1, 0], [1, 0, 1], [0, 0, 1], [1, 1, 0])
        chain = synthetic_converged_chain(entry, half_nm, step_nm;
            sequence=true_sequence, mold_amp=0.4)
        result = search_whole_roi_sequences(chain.observed, chain.backbone,
            entry, chain.centers, chain.xs, chain.ys;
            half_nm=half_nm, step_nm=step_nm, theta=chain.theta,
            directions=(chain.direction,), phases=(chain.phase,),
            mirrors=(chain.mirror,), max_n=8)
        recovered = result.sequence == true_sequence
        println("  sequence $(true_sequence): recovered=$(recovered) ",
                "sse=$(@sprintf("%.4e", result.fit.sse)) ",
                "mold_coeff=$(@sprintf("%.4f", result.fit.mold_coefficient))")
    end

    # Test 2: recovery under noise
    println()
    for noise in (0.0, 0.01, 0.05, 0.10)
        chain = synthetic_converged_chain(entry, half_nm, step_nm;
            sequence=[0, 1, 0], mold_amp=0.4, noise_sigma=noise)
        result = search_whole_roi_sequences(chain.observed, chain.backbone,
            entry, chain.centers, chain.xs, chain.ys;
            half_nm=half_nm, step_nm=step_nm, theta=chain.theta,
            directions=(chain.direction,), phases=(chain.phase,),
            mirrors=(chain.mirror,), max_n=8)
        recovered = result.sequence == [0, 1, 0]
        println("  noise=$noise: recovered=$recovered ",
                "sse=$(@sprintf("%.4e", result.fit.sse)) ",
                "mold_coeff=$(@sprintf("%.4f", result.fit.mold_coefficient))")
    end

    # Test 3: mold discriminability (correct vs swapped)
    println()
    chain = synthetic_converged_chain(entry, half_nm, step_nm;
        sequence=[0, 1, 0], mold_amp=0.4)
    correct_mold = assemble_whole_roi(entry, [0, 1, 0], chain.centers,
        chain.xs, chain.ys; half_nm=half_nm, step_nm=step_nm,
        theta=chain.theta, direction=chain.direction, phase=chain.phase,
        mirror=chain.mirror)
    swapped_mold = assemble_whole_roi(entry, [1, 0, 1], chain.centers,
        chain.xs, chain.ys; half_nm=half_nm, step_nm=step_nm,
        theta=chain.theta, direction=chain.direction, phase=chain.phase,
        mirror=chain.mirror)
    correct_fit = fit_whole_roi_nuisance(chain.observed, chain.backbone, correct_mold)
    swapped_fit = fit_whole_roi_nuisance(chain.observed, chain.backbone, swapped_mold)
    ratio = swapped_fit.sse / max(correct_fit.sse, 1e-30)
    println("  discriminability:")
    println("    correct sequence SSE: ", @sprintf("%.4e", correct_fit.sse))
    println("    swapped  sequence SSE: ", @sprintf("%.4e", swapped_fit.sse))
    println("    ratio swapped/correct: ", @sprintf("%.2f", ratio))
    println("    mold coefficient (correct): ", @sprintf("%.4f", correct_fit.mold_coefficient))
    println()
    println("Decision: $(ratio > 1.0 ? "converged molds are type-discriminative" : "insufficient discrimination")")
end

main()
