#!/usr/bin/env julia

# Import simulated STM/LDOS maps as connected GlcN/GlcNAc mold templates.
#
# The input is a long TSV in the aligned lobe frame:
#   type  t_nm  u_nm  value  [parity]  [mirror]
# where type=0 is GlcN and type=1 is GlcNAc. If parity/mirror rows are not
# supplied, the script generates them by flipping the base map according to the
# same global connectivity convention used by score_connected_mold_templates.jl.
#
# Optional bond maps can be supplied in long form:
#   left_type  right_type  side  t_nm  u_nm  value  [parity]  [mirror]
# where side is left/right (or l/r). If --bond-out is requested without
# --bond-maps, bond templates are generated by concatenating unary templates.

using Printf
using Statistics

include(joinpath(@__DIR__, "lib", "script_utils.jl"))
using .ScriptUtils: _ensure_parent, _parse_f, _read_tsv

const DEFAULT_MAPS = "templates/chitosan_stm_maps.tsv"
const DEFAULT_OUT = "templates/chitosan_connected_molds_stm.tsv"

struct Options
    maps::String
    out_tsv::String
    bond_maps::Union{Nothing,String}
    bond_out_tsv::String
    half_nm::Float64
    step_nm::Float64
    parity_flip::String
    mirror_flip::String
    normalize::String
end

struct GridMap
    ts::Vector{Float64}
    us::Vector{Float64}
    z::Matrix{Float64}  # rows = u, columns = t
end

function _parse_cli(args)
    maps = DEFAULT_MAPS
    out_tsv = DEFAULT_OUT
    bond_maps::Union{Nothing,String} = nothing
    bond_out_tsv = ""
    half_nm = 0.48
    step_nm = 0.08
    parity_flip = "t"
    mirror_flip = "u"
    normalize = "zscore"
    i = 1
    while i <= length(args)
        arg = args[i]
        if arg == "--maps"; maps = args[i+1]; i += 2
        elseif startswith(arg, "--maps="); maps = split(arg, "=", limit=2)[2]; i += 1
        elseif arg == "--out"; out_tsv = args[i+1]; i += 2
        elseif startswith(arg, "--out="); out_tsv = split(arg, "=", limit=2)[2]; i += 1
        elseif arg == "--bond-maps"; bond_maps = args[i+1]; i += 2
        elseif startswith(arg, "--bond-maps="); bond_maps = split(arg, "=", limit=2)[2]; i += 1
        elseif arg == "--bond-out"; bond_out_tsv = args[i+1]; i += 2
        elseif startswith(arg, "--bond-out="); bond_out_tsv = split(arg, "=", limit=2)[2]; i += 1
        elseif arg == "--half-nm"; half_nm = parse(Float64, args[i+1]); i += 2
        elseif startswith(arg, "--half-nm="); half_nm = parse(Float64, split(arg, "=", limit=2)[2]); i += 1
        elseif arg == "--step-nm"; step_nm = parse(Float64, args[i+1]); i += 2
        elseif startswith(arg, "--step-nm="); step_nm = parse(Float64, split(arg, "=", limit=2)[2]); i += 1
        elseif arg == "--parity-flip"; parity_flip = args[i+1]; i += 2
        elseif startswith(arg, "--parity-flip="); parity_flip = split(arg, "=", limit=2)[2]; i += 1
        elseif arg == "--mirror-flip"; mirror_flip = args[i+1]; i += 2
        elseif startswith(arg, "--mirror-flip="); mirror_flip = split(arg, "=", limit=2)[2]; i += 1
        elseif arg == "--normalize"; normalize = args[i+1]; i += 2
        elseif startswith(arg, "--normalize="); normalize = split(arg, "=", limit=2)[2]; i += 1
        elseif arg in ("-h", "--help")
            println("""
            Usage: julia --project=. test/import_stm_mold_maps.jl [options]

            Options:
              --maps PATH          Long unary STM/LDOS map TSV [$(DEFAULT_MAPS)]
              --out PATH           Output connected mold TSV [$(DEFAULT_OUT)]
              --bond-maps PATH     Optional long bond-map TSV
              --bond-out PATH      Optional output sliding bond template TSV
              --half-nm FLOAT      Template half-size [0.48]
              --step-nm FLOAT      Template grid spacing [0.08]
              --parity-flip STR    none | t | u | both [t]
              --mirror-flip STR    none | t | u | both [u]
              --normalize STR      none | sum | max | zscore [zscore]

            Unary map TSV columns:
              type, t_nm, u_nm, value, optional parity, optional mirror

            Bond map TSV columns:
              left_type, right_type, side, t_nm, u_nm, value,
              optional parity, optional mirror

            Notes:
              The maps must already be in the aligned patch frame: t along the
              beta-(1->4) backbone, u transverse, and origin at the central lobe.
              Truth labels and composition counts are never read.
            """)
            exit(0)
        else
            error("Unknown argument: $arg")
        end
    end
    isfile(maps) || error("Map TSV not found: $maps")
    bond_maps !== nothing && !isfile(bond_maps) && error("Bond map TSV not found: $bond_maps")
    parity_flip in ("none", "t", "u", "both") || error("Invalid --parity-flip")
    mirror_flip in ("none", "t", "u", "both") || error("Invalid --mirror-flip")
    normalize in ("none", "sum", "max", "zscore") || error("Invalid --normalize")
    half_nm > 0 || error("--half-nm must be positive")
    step_nm > 0 || error("--step-nm must be positive")
    return Options(maps, out_tsv, bond_maps, bond_out_tsv, half_nm, step_nm,
                   parity_flip, mirror_flip, normalize)
end

_parse_i(s) = round(Int, _parse_f(s))

function _has_columns(header, required)
    missing = [c for c in required if !(c in header)]
    isempty(missing) || error("Missing columns: $(join(missing, ", "))")
end

function _apply_flip(t, u, spec::String)
    spec == "none" && return t, u
    spec == "t" && return -t, u
    spec == "u" && return t, -u
    return -t, -u
end

function _inverse_oriented_coord(t, u, parity::Int, mirror::Int, opt::Options)
    # Flips are their own inverse. Undo mirror first, then parity, matching the
    # generation order used by generate_connected_mold_templates.jl.
    mirror == 1 && ((t, u) = _apply_flip(t, u, opt.mirror_flip))
    parity == 1 && ((t, u) = _apply_flip(t, u, opt.parity_flip))
    return t, u
end

function _normalize(v::Vector{Float64}, method::String)
    method == "none" && return v
    good = filter(isfinite, v)
    isempty(good) && return v
    if method == "sum"
        s = sum(abs, good)
        return s > 0 ? [isfinite(x) ? x / s : NaN for x in v] : v
    elseif method == "max"
        m = maximum(abs.(good))
        return m > 0 ? [isfinite(x) ? x / m : NaN for x in v] : v
    end
    μ = mean(good)
    σ = std(good)
    σ = σ > 0 ? σ : 1.0
    return [isfinite(x) ? (x - μ) / σ : NaN for x in v]
end

function _make_grid(points::Vector{Tuple{Float64,Float64,Float64}})
    ts = sort(unique(first.(points)))
    us = sort(unique(p[2] for p in points))
    isempty(ts) && error("empty map")
    z = fill(NaN, length(us), length(ts))
    ti = Dict(t => i for (i, t) in enumerate(ts))
    ui = Dict(u => i for (i, u) in enumerate(us))
    for (t, u, v) in points
        z[ui[u], ti[t]] = v
    end
    return GridMap(ts, us, z)
end

function _interp(g::GridMap, t::Float64, u::Float64)
    if t < first(g.ts) || t > last(g.ts) || u < first(g.us) || u > last(g.us)
        return NaN
    end
    it = searchsortedlast(g.ts, t)
    iu = searchsortedlast(g.us, u)
    it == length(g.ts) && (it -= 1)
    iu == length(g.us) && (iu -= 1)
    if it < 1 || iu < 1 || it >= length(g.ts) || iu >= length(g.us)
        return NaN
    end
    t1, t2 = g.ts[it], g.ts[it+1]
    u1, u2 = g.us[iu], g.us[iu+1]
    dt = t2 == t1 ? 0.0 : (t - t1) / (t2 - t1)
    du = u2 == u1 ? 0.0 : (u - u1) / (u2 - u1)
    z11 = g.z[iu, it]
    z21 = g.z[iu, it+1]
    z12 = g.z[iu+1, it]
    z22 = g.z[iu+1, it+1]
    any(!isfinite, (z11, z21, z12, z22)) && return NaN
    return (1-dt)*(1-du)*z11 + dt*(1-du)*z21 + (1-dt)*du*z12 + dt*du*z22
end

function _load_unary_maps(path::String)
    header, rows = _read_tsv(path)
    _has_columns(header, ["type", "t_nm", "u_nm", "value"])
    grouped = Dict{Tuple{Int,Int,Int},Vector{Tuple{Float64,Float64,Float64}}}()
    has_parity = "parity" in header
    has_mirror = "mirror" in header
    for row in rows
        typ = _parse_i(row["type"])
        typ in (0, 1) || error("type must be 0 or 1")
        parity = has_parity && !isempty(strip(row["parity"])) ? _parse_i(row["parity"]) : 0
        mirror = has_mirror && !isempty(strip(row["mirror"])) ? _parse_i(row["mirror"]) : 0
        parity in (0, 1) || error("parity must be 0 or 1")
        mirror in (0, 1) || error("mirror must be 0 or 1")
        push!(get!(grouped, (typ, parity, mirror), Tuple{Float64,Float64,Float64}[]),
              (_parse_f(row["t_nm"]), _parse_f(row["u_nm"]), _parse_f(row["value"])))
    end
    maps = Dict(k => _make_grid(v) for (k, v) in grouped)
    for typ in (0, 1)
        haskey(maps, (typ, 0, 0)) || error("Missing base unary map type=$typ parity=0 mirror=0")
    end
    return maps
end

function _unary_template(maps, typ::Int, parity::Int, mirror::Int, coords, opt::Options)
    if haskey(maps, (typ, parity, mirror))
        grid = maps[(typ, parity, mirror)]
        vals = [_interp(grid, t, u) for u in coords for t in coords]
    else
        grid = maps[(typ, 0, 0)]
        vals = Float64[]
        for u in coords, t in coords
            bt, bu = _inverse_oriented_coord(t, u, parity, mirror, opt)
            push!(vals, _interp(grid, bt, bu))
        end
    end
    return _normalize(vals, opt.normalize)
end

function _load_bond_maps(path::String)
    header, rows = _read_tsv(path)
    _has_columns(header, ["left_type", "right_type", "side", "t_nm", "u_nm", "value"])
    has_parity = "parity" in header
    has_mirror = "mirror" in header
    grouped = Dict{Tuple{Int,Int,Int,Int,String},Vector{Tuple{Float64,Float64,Float64}}}()
    for row in rows
        lt = _parse_i(row["left_type"])
        rt = _parse_i(row["right_type"])
        lt in (0, 1) || error("left_type must be 0 or 1")
        rt in (0, 1) || error("right_type must be 0 or 1")
        side_raw = lowercase(strip(row["side"]))
        side = side_raw in ("left", "l") ? "l" : side_raw in ("right", "r") ? "r" : error("side must be left/right or l/r")
        parity = has_parity && !isempty(strip(row["parity"])) ? _parse_i(row["parity"]) : 0
        mirror = has_mirror && !isempty(strip(row["mirror"])) ? _parse_i(row["mirror"]) : 0
        parity in (0, 1) || error("parity must be 0 or 1")
        mirror in (0, 1) || error("mirror must be 0 or 1")
        push!(get!(grouped, (lt, rt, parity, mirror, side), Tuple{Float64,Float64,Float64}[]),
              (_parse_f(row["t_nm"]), _parse_f(row["u_nm"]), _parse_f(row["value"])))
    end
    maps = Dict(k => _make_grid(v) for (k, v) in grouped)
    for lt in (0, 1), rt in (0, 1), side in ("l", "r")
        haskey(maps, (lt, rt, 0, 0, side)) || error("Missing base bond map left=$lt right=$rt side=$side")
    end
    return maps
end

function _bond_side_template(maps, lt::Int, rt::Int, parity::Int, mirror::Int, side::String, coords, opt::Options)
    if haskey(maps, (lt, rt, parity, mirror, side))
        grid = maps[(lt, rt, parity, mirror, side)]
        vals = [_interp(grid, t, u) for u in coords for t in coords]
    else
        grid = maps[(lt, rt, 0, 0, side)]
        vals = Float64[]
        for u in coords, t in coords
            bt, bu = _inverse_oriented_coord(t, u, parity, mirror, opt)
            push!(vals, _interp(grid, bt, bu))
        end
    end
    return _normalize(vals, opt.normalize)
end

_fmt(v) = isfinite(v) ? @sprintf("%.8g", v) : "NA"

function main()
    opt = _parse_cli(ARGS)
    unary_maps = _load_unary_maps(opt.maps)
    coords = collect(-opt.half_nm:opt.step_nm:opt.half_nm)
    pix = [@sprintf("p%03d", i) for i in 1:(length(coords)^2)]

    unary_templates = Dict{Tuple{Int,Int,Int},Vector{Float64}}()
    for typ in (0, 1), parity in (0, 1), mirror in (0, 1)
        unary_templates[(typ, parity, mirror)] = _unary_template(unary_maps, typ, parity, mirror, coords, opt)
    end

    _ensure_parent(opt.out_tsv)
    open(opt.out_tsv, "w") do io
        println(io, join(vcat(["name", "type", "parity", "mirror"], pix), '\t'))
        for typ in (0, 1), parity in (0, 1), mirror in (0, 1)
            name = @sprintf("%s_p%d_m%d", typ == 0 ? "GlcN" : "GlcNAc", parity, mirror)
            vals = unary_templates[(typ, parity, mirror)]
            println(io, join(vcat([name, string(typ), string(parity), string(mirror)], [_fmt(v) for v in vals]), '\t'))
        end
    end

    if !isempty(opt.bond_out_tsv)
        _ensure_parent(opt.bond_out_tsv)
        left_pix = ["l_$(p)" for p in pix]
        right_pix = ["r_$(p)" for p in pix]
        bond_maps = opt.bond_maps === nothing ? nothing : _load_bond_maps(opt.bond_maps)
        open(opt.bond_out_tsv, "w") do io
            println(io, join(vcat(["name", "left_type", "right_type", "parity", "mirror"], left_pix, right_pix), '\t'))
            for lt in (0, 1), rt in (0, 1), parity in (0, 1), mirror in (0, 1)
                if bond_maps === nothing
                    left_vals = unary_templates[(lt, parity, mirror)]
                    right_vals = unary_templates[(rt, 1 - parity, mirror)]
                else
                    left_vals = _bond_side_template(bond_maps, lt, rt, parity, mirror, "l", coords, opt)
                    right_vals = _bond_side_template(bond_maps, lt, rt, parity, mirror, "r", coords, opt)
                end
                name = @sprintf("%d%d_p%d_m%d", lt, rt, parity, mirror)
                println(io, join(vcat([name, string(lt), string(rt), string(parity), string(mirror)],
                                      [_fmt(v) for v in left_vals], [_fmt(v) for v in right_vals]), '\t'))
            end
        end
    end

    println("Imported STM/LDOS mold maps")
    println("  maps:      ", opt.maps)
    println("  output:    ", opt.out_tsv)
    !isempty(opt.bond_out_tsv) && println("  bond out:  ", opt.bond_out_tsv)
    opt.bond_maps !== nothing && println("  bond maps: ", opt.bond_maps)
    println("  grid:      ", length(coords), "x", length(coords), " (", length(pix), " pixels)")
    println("  parity:    ", opt.parity_flip)
    println("  mirror:    ", opt.mirror_flip)
    println("  normalize: ", opt.normalize)
end

main()
