name = "STMFitCore"
uuid = "4d8f3c22-9b76-4f91-a75b-40a4f4a6a001"
version = "0.1.0"
authors = ["OD"]

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.10"
